### PR TITLE
StopTheHostException is now called HostAbortedException

### PR DESCRIPTION
**Pull request by AkosLukacs**

### CODE REVIEW

**Comment by AkosLukacs** [comment]
Link to the merged PR from the mentioned issue: https://github.com/dotnet/runtime/pull/69404

**Comment by brockallen** [comment]
This was done in .NET 7 I take it?

**Comment by AkosLukacs** [comment]
> This was done in .NET 7 I take it?

I'm testing with .NET 6, and looks like the exception thrown depends on the version of `Microsoft.EntityFrameworkCore.Tools` package: v7.xx throws `HostAbortedException`. Going through the samples now installs v7 of `Microsoft.EntityFrameworkCore.Tools` on .NET 6.
v6.xx throws `StopTheHostException`. To make things straight forward...

**Comment by brockallen** [comment]
Ok, got it. So for the time being we have to handle both :) 

Thanks!

**Comment by AkosLukacs** [comment]
Maybe this is a good enough description? Felt like a quick and easy PR :D

**Comment by brockallen** [comment]
Yep, thanks for this! We also have other places we need to update with this, so we'll work on that. Thanks again!

**Comment by josephdecock** [comment]
Related - https://github.com/DuendeSoftware/Samples/pull/103 updates the reference implementations of QS 4, 5 to use this.

**Review by josephdecock — APPROVED** [review]
Just made a minor change to clarify usage of version numbers and to match our template source code.

**Pull request merged**
