### PR TITLE
Updates various references.

### PR DESCRIPTION
**Pull request by tim-schmidt**
Removes '--prerelease' from Duende.BFF reference.
Adds reference to Duende.BFF.Yarp.
Refactors to reference Program.cs instead of Startup.cs.
Refactors to reference app.js instead of site.js.

### CODE REVIEW

**Comment by tim-schmidt** [comment]
Just wanted to say I have loved IdentityServer for quite some time! Glad I can contribute at least a little.

**Comment by tim-schmidt** [comment]
Also, every time I see the acronym "yarp" I can't help but think of Hot Fuzz.

**Comment by leastprivilege** [comment]
Thanks! @josephdecock is the master of docs. I let him comment.

**Comment by josephdecock** [comment]
@tim-schmidt - Thanks so much for your contribution! I have used your commit as the starting point of a larger edit of the quickstart, so I'm closing this PR, but your changes - along with other edits - will go in PR #110. Again, thanks very much for contributing!

**Pull request closed without merging**
