### PR TITLE
Update 4_ef.md for EF migration fixes. 

### PR DESCRIPTION
**Pull request by aniketrai**
Updated catch block. It needs to un handle two exceptions in order to run migration successfully.

### CODE REVIEW

**Comment by brockallen** [comment]
Hi @aniketrai -- can you elaborate on how you ran across this? Is this something new/different in .NET 7, perhaps?

**Comment by brockallen** [comment]
Also, if this change is necessary, then this is the wrong place -- it should be done in our templates.  // @josephdecock

**Comment by brockallen** [comment]
Hey @aniketrai. Not sure why you closed -- can you provide some more context here to the question I asked?

> can you elaborate on how you ran across this? Is this something new/different in .NET 7, perhaps?

**Comment by aniketrai** [comment]
Earlier it was not working and was throwing the HostAbortedException. I tried again today after removing this condition, everything was working fine. Not sure about the cause of the issue.

**Comment by brockallen** [comment]
Oh ok... thanks for the follow up!

**Pull request closed without merging**
