### PR TITLE
Update di.md

### PR DESCRIPTION
**Pull request by StuFrankish**
Tiny update to change to remove the extraneous "a" from [Adds a an “AppAuth”].

### CODE REVIEW

**Review by josephdecock — COMMENTED** [review]
Thanks!

**Review by josephdecock — APPROVED** [review]

**Comment by brockallen** [comment]
My only thought here is that this was fixed in the v5 docs... those are pretty much retired. We have 2 other "branches" now... does this need to get reflected there as well?

**Comment by StuFrankish** [comment]
@brockallen I'll raise a quick PR for those now as well 👍

**Comment by StuFrankish** [comment]
Raised a new PR for V6 - https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/375  and V7 https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/376

**Pull request merged**
