### PR TITLE
Adds some missing `--` in command samples 

### PR DESCRIPTION
**Pull request by henriksen**
Add `--` to `install` parameter

### CODE REVIEW

**Comment by brockallen** [comment]
Hi @henriksen!

Anyway, I don't know what to believe these days :)

https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/278

**Comment by josephdecock** [comment]
@henricksen What version of the dotnet cli are you using?

**Comment by henriksen** [comment]
Well, there you go. I'm just behind on versions... 

In `dotnet` version 6, I need the dashes, but on `dotnet`version 7, I get a warning that the dashes are deprecated.  

I'd argue to keep the dashes a bit more since 6 is an LTS version and it doesn't work on 6 without them. Once 8 is released it's more reasonable to drop the dashes.

Or drop them and offer an explanation that you have to use dashes on version 6.

**Comment by josephdecock** [comment]
Thanks very much @henriksen!

**Review by josephdecock — APPROVED** [review]

**Comment by oscarlofwenhamn** [comment]
Literally just about to create a PR to "use `install` instead of deprecated `--install`" when I thought to check if there was some history, guess I'll hold on to it. 😅

Unless something like 
```
# dotnet 7+
dotnet new install Duende.IdentityServer.Templates

# dotnet 6
dotnet new --install Duende.IdentityServer.Templates
```
would be a decent middle ground to safeguard against future "helpful PRs", in which case I've got one ready.

**Pull request merged**
